name: 'PR'

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: 현재 PR 브랜치 이름

      - name: Check Diff
        shell: bash
        run: |
          DIFF=$(git diff --name-only HEAD master)

          IS_REVIEW_RELEASE=true

          for x in $DIFF
          do
            echo $x
            if [[ $x == *.ios* ]]
            then
              is_review_relase=false
              break
            fi
          done

          echo $is_review_relase
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV