name: "PR"

on:
  pull_request:
    types: [opened]
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.base_ref }}

      - name: Check Diff and Verifying release
        shell: bash
        run: |
          DIFF=$(git diff --name-only HEAD master)

          IS_REVIEW_RELEASE=true

          for diff in $DIFF
          do
            echo $diff
            if [[ $diff == *android* ]] || [[ $diff == *ios* ]]
            then
              IS_REVIEW_RELEASE=false
              break
            fi
          done

          echo $IS_REVIEW_RELEASE
          echo "ENV_IS_REVIEW_RELEASE=$IS_REVIEW_RELEASE" >> $GITHUB_ENV

      - name: Get Latest Release tag name
        shell: bash
        run: |
          LATEST_RELEASE=$(curl --silent -i -u username:${{ secrets.ACCESS_TOKEN }} "https://api.github.com/repos/MaxKim-J/actions-node-which/releases/latest" | grep '"tag_name":' | sed -E 's/"tag_name": "(.+)"\,/\1/')
          echo $LATEST_RELEASE

          echo "ENV_LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Get current release version
        shell: bash
        run: |
          if [ ${ENV_IS_REVIEW_RELEASE} = true ]; then
            NEW_RELEASE_VERSION=v$(grep "versionName \"[1-9].[0-9].[0-9]\"" android/app/build.gradle | tr -d ' ' | cut -c 13-17 )
          else
            if [ ${ENV_LATEST_RELEASE:6} != '' ]; then
              NEW_MINOR_FIGURE=$(echo "${LATEST_VERSION:6}" | tr "0-9a-z" "1-9a-z_")
              NEW_RELEASE_VERSION=${LATEST_VERSION:1:5}${NEW_MINOR_FIGURE}
            else
              NEW_RELEASE_VERSION=${LATEST_VERSION}a
            fi
          fi

          echo $NEW_RELEASE_VERSION
          echo "ENV_NEW_RELEASE_VERSION=$NEW_RELEASE_VERSION" >> $GITHUB_ENV

      # 이미 있으면 안만들어야 되네
      - name: Make Draft release
        run: |
          curl \ 
          -X POST \ 
          --silent -i -u username:${{ secrets.ACCESS_TOKEN }} \ 
          "https://api.github.com/repos/MaxKim-J/actions-node-which/releases/latest" \
          -d '{"tag_name":${ENV_NEW_RELEASE_VERSION}, "name":${ENV_NEW_RELEASE_VERSION}}'
