name: 'PR'

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: 현재 PR 브랜치 이름

      - name: Check Diff
        run: |
          DIFF=($(git diff --name-only 현재브랜치PR의헤드 master브랜치PR의헤드))
          for x in $DIFF
          do
            echo $x
            echo '으앙..'
          done